name: Test Secret

on:
  push:
  workflow_dispatch:   

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secret
        run: |
          if [ -z "$API_KEY" ]; then
            echo "Secret NOT working"
          else
            echo "Secret working"
          fi
        env:
          API_KEY: ${{ secrets.API_KEY }}
